# This is a basic workflow to help you get started with Actions

name: reviewdog

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # 構文チェック
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # ①
      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
      # ②
      - name: code snifffer install
        run: composer require squizlabs/php_codesniffer
      - name: lint
        # ③
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # ④
        run: ./vendor/bin/phpcs --report=emacs --standard=phpcs.xml ./ | reviewdog -reporter=github-pr-review -efm='%f:%l:%c:%m'

# 静的解析
  analyse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # ①
      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
      # ②
      - name: phpstan install
        run: composer require phpstan/phpstan
      - name: analyse
        env:
          # ③
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # ④
        run: ./vendor/bin/phpstan analyse --error-format=raw --no-progress -l 5 index.php | reviewdog -reporter=github-pr-review -f=phpstan
